### ISSUE TITLE
Unable to copy scoped packages

### ISSUE THREAD

**Issue by fireflycons** [goodeggs/npm-copy#5]
Hi,
I'm using this to migrate packages from Proget to Nexus RM 3.13.0-01. All unscoped packages migrate fine,  however scoped ones throw an exception thus:

```
npm-copy --from https://proget.redacted.com/npm/private-npm --from-username XXX --from-password XXX --to https://nxrm.redacted.com/repository/npm-private --to-username XXX --to-password XXX --to-email XXX@XXX.com @my_scope/my_component

info attempt registry request try #1 at 8:18:26 AM
http request GET https://proget.redacted.com/npm/private-npm/@my_scope/my_component
http 200 https://proget.redacted.com/npm/private-npm/@my_scope/my_component
info attempt registry request try #1 at 8:18:28 AM
http request GET https://nxrm.redacted.com/repository/npm-private/@my_scope/my_component
http 404 https://nxrm.redacted.com/repository/npm-private/@my_scope/my_component
info attempt registry request try #1 at 8:18:28 AM
http fetch GET https://proget.redacted.com/npm/private-npm/@my_scope/my_component/-/my_component-0.0.31.tgz
http fetch 200 https://proget.redacted.com/npm/private-npm/@my_scope/my_component/-/my_component-0.0.31.tgz
info attempt registry request try #1 at 8:18:28 AM
http request PUT https://nxrm.redacted.com/repository/npm-private/@my_scope/@my_scope%2fmy_component
http 400 https://nxrm.redacted.com/repository/npm-private/@my_scope/@my_scope%2fmy_component
ERR! publish Failed PUT 400
Error: 400 Bad Request
    at Object.wait (/usr/lib/node_modules/npm-copy/node_modules/fibers/future.js:449:15)
    at RegClient.<anonymous> (/usr/lib/node_modules/npm-copy/node_modules/fibrous/lib/fibrous.js:66:47)
    at Object.publish (/usr/lib/node_modules/npm-copy/node_modules/fibrous/lib/fibrous.js:101:47)
    at /usr/lib/node_modules/npm-copy/lib/cli.js:84:26
    at /usr/lib/node_modules/npm-copy/lib/cli.js:101:7
    at /usr/lib/node_modules/npm-copy/node_modules/fibers/future.js:467:21
    - - - - -
    at makeError (/usr/lib/node_modules/npm-copy/node_modules/npm-registry-client/lib/request.js:329:12)
    at RegClient.<anonymous> (/usr/lib/node_modules/npm-copy/node_modules/npm-registry-client/lib/request.js:259:9)
    at Request._callback (/usr/lib/node_modules/npm-copy/node_modules/npm-registry-client/lib/request.js:216:14)
    at Request.self.callback (/usr/lib/node_modules/npm-copy/node_modules/request/request.js:185:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/usr/lib/node_modules/npm-copy/node_modules/request/request.js:1161:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/usr/lib/node_modules/npm-copy/node_modules/request/request.js:1083:12)
```

TIA.

**Comment by bobzoller** [comment]
We're not actively maintaining this package at the moment, but I'm happy to merge passing PRs or discuss a change in ownership.

**Comment by dtjohnson** [comment]
I figured out how to make it work with scoped packages. You just need to escape the `/` in the package name. So just change `@my_scope/my_component` to `@my_scope%2fmy_component`.

Thanks, @bobzoller for making this module available. You saved my bacon.

**Comment by dperuo** [comment]
For what it's worth, we cloned this project and made some updates: https://www.npmjs.com/package/@appsweet-co/npm-carbon

We will actively maintain the new `@appsweet-co/npm-carbon` package.
